### ISSUE TITLE
Is this package welcoming contributions ?

### ISSUE THREAD

**Issue by ewjoachim** [djpugh/sphinx-gh-changelog#1]
Hi,

I think we were trying to solve same problem and came to the same solution (creating a Changelog sphinx directive based on the content of github releases), except I did a quick and dirty in the package I was building (https://github.com/peopledoc/procrastinate/blob/master/docs/sphinxext/changelog.py which generates https://procrastinate.readthedocs.io/en/stable/changelog.html) with the intent on putting this in its own package someday.

On the other hand, it seems you already went through much of that with cleaner and more modular code, already in a dedicated repo and packaged. But it seems not to have been released on pypi.

Instead of putting my efforts polishing my script into a package, I'm wondering if we could collaborate and work ok yours instead. I believe we're missing a few things:

- A readme
- Publish on PyPI
- Document the usage of the directive
- Drink our own champagne: publish this tool's doc on readthedocs and have this tool's changelog be a showcase of the tool
- The repo you built this for seems hardcoded in [some places](https://github.com/djpugh/sphinx-gh-changelog/blob/master/src/release_changelog/providers/github.py#L37)
- Not sure what versionneer and _version.py do in this repo ...?

Also I'll need to understand what magic you used to get HTML chunks from GitHub, I could only get markdown except if I used graphql which cannot be anonymous, so I'm still wondering how you pulled that.

Well tell me if you're interested in me spending some time on those things.

**Comment by ewjoachim** [comment]
(oh BTW if you're publishing to PyPI, it's all your choice but I have to admit I like the name `sphinx-gh-changelog` (the current github repo name) much better than `release_changelog` (the current name in setup.py)

**Comment by djpugh** [comment]
@ewjoachim absolutely - I started this a bit as you can see - its sort of working, then I ran out of spare time to keep working on it - keen to support and come back to it - and sort out as above (I started to build it when I started playing around with Github actions)

A few things - versioneer/version.py  this is setting the version directly from git tags rather than anything else (builds it into the _version.py file when building an sdist/bdist)
This is coupling up with release drafter for the change notices (https://github.com/djpugh/sphinx-gh-changelog/blob/master/.github/workflows/release-management.yaml)

**Comment by ewjoachim** [comment]
I also use release drafter in procrastinate ;)

For versioneer: I use a smaller piece of code in setup.py:

https://github.com/peopledoc/procrastinate/blob/35e926b2c26abe96c5ad17d06e1b775500a633c8/setup.py#L9-41

and I plan to go even smaller with [Setuptools-scm](https://pypi.org/project/setuptools-scm/). I can understand that this could feel strange because it adds a `setup_requires` dependency, but I like how this lets me remove code that has nothing to do with the problem from the repo.

I’ll try to start contributing :)

**Comment by ewjoachim** [comment]
Ok so the magic that lets you receive markdown bodies, and change them into rst is https://github.com/djpugh/sphinx-gh-changelog/blob/615849a57e1a9096f651b52a28eb8c889664a3e3/src/release_changelog/providers/_base.py#L40-L49 .

This won't support links, (including links to tickets: #XXX). I see you deal with this later, but only support tickets wen enclosed in parentheses.

**Comment by ewjoachim** [comment]
Ok, reading the code more in depth, I realize what I'm after is probably a middleground between your code and my code. I think I'll start a project on my own but I'll be inspired from your code. I'll add an ack and if you want (or depending on whether I end up copy/pasting code from your repo), in the licence :)

**Comment by djpugh** [comment]
This isn't particularly widely used - I was trying to solve this problem quickly and see if it worked - I'm definitely keen to make it better/more robust for md > rst (i was thinking about docutils), so if you'd still like to work within it, feel free (or point me at your)

**Comment by ewjoachim** [comment]
I’ll point to my repo as soon as I have anything to show :)

Thanks a lot (for your code, yours answers, everything)

**Comment by ewjoachim** [comment]
Hi :) I'm going to merge this probably today, but you're very welcome to do a pre-merge or post-merge review :)

https://github.com/peopledoc/sphinx-github-changelog/pull/2

I think I'll probably start using it right away.
